services:
  pii-redactor:
    build: .
    image: piiredactor.azurecr.io/pii-redactor:latest
    container_name: pii_redactor_app
    ports:
      - "80:80"
    environment:
      - PORT=80
    restart: always
    volumes:
      - pii_cache:/app/tmp_cache

volumes:
  pii_cache:
